   
    REACT_APP_AWS_PROJECT_REGION: "${AWS_DEFAULT_REGION}"

    REACT_APP_AWS_COGNITO_REGION: "${AWS_DEFAULT_REGION}"

    REACT_APP_AWS_USER_POOLS_ID: "us-east-1_2cSl53AWS"

    REACT_APP_CLIENT_ID: '2v4gvu7k29d2ggv7q4tam78uva'
    
